// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDesktopShortcut(arg1) {
  return window['go']['main']['App']['CreateDesktopShortcut'](arg1);
}

export function InstallApp(arg1, arg2) {
  return window['go']['main']['App']['InstallApp'](arg1, arg2);
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
