// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDesktopShortcut(arg1:string):Promise<string>;

export function InstallApp(arg1:string,arg2:boolean):Promise<string>;

export function LaunchApp(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;
